### PR TITLE
Fix/downgrade lib

### PR DESCRIPTION
**Pull request by ArtemTrofimushkin**

### CODE REVIEW

**Review by shmel1k — APPROVED** [review]

**Comment by ArtemTrofimushkin** [comment]
WTF

Running [/home/runner/golangci-lint-1.61.0-linux-amd64/golangci-lint run] in [/home/runner/work/ydbops/ydbops] ...
  Received 640472 of 640472 (100.0%), 0.6 MBs/sec
  go.mod:77:1: replacement are not allowed: google.golang.org/grpc (gomoddirectives)
  
  level=warning msg="[runner/source_code] Failed to get line 77 for file go.mod: invalid file line index0 (76) >= len(fc) (75)"

https://github.com/ydb-platform/ydbops/pull/54/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R75

**Comment by Jorres** [comment]
Ok, let's merge, maybe it's some remaning state from this particular branch. But if linter will fail after merge to trunk still, please debug and fix this @ArtemTrofimushkin

**Comment by ArtemTrofimushkin** [comment]
@Jorres Sure!

**Comment by ArtemTrofimushkin** [comment]
https://github.com/ydb-platform/ydbops/actions/runs/12429927506/job/34704349467

**Pull request merged**
